server:
  port: 8002
spring:
  application:
    name: oss-service
  profiles:
    active: dev

aliyun:
  oss:
    file:
      endpoint: 
      keyid: 
      keysecret: 
      bucketname: guli-college-mirai
